"""Initial control-plane schema: 3 enums + 5 tables.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-06

Hand-written rather than autogenerated, for one reason: ordering. Autogenerate
emits CREATE TYPE inline with the first table that references an enum, which
breaks as soon as a second table uses the same type (health_status is on both
`clusters` and `health_checks`) and leaves the drop order undefined. Here all
three types are created up front and dropped last, and every column referencing
them uses create_type=False so nothing tries to create them a second time.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- enum definitions ----------------------------------------------------
# create_type=False: creation and removal are driven explicitly below, never as
# a side effect of a column definition.
DEPLOYMENT_TYPE = postgresql.ENUM(
    "docker_standalone",
    "docker_distributed",
    "k8s_operator",
    name="deployment_type",
    create_type=False,
)
DEPLOYMENT_STATUS = postgresql.ENUM(
    "pending",
    "provisioning",
    "running",
    "degraded",
    "unavailable",
    "stopped",
    "deleted",
    name="deployment_status",
    create_type=False,
)
HEALTH_STATUS = postgresql.ENUM(
    "healthy",
    "degraded",
    "unavailable",
    "unknown",
    name="health_status",
    create_type=False,
)

TZ = sa.TIMESTAMP(timezone=True)


def upgrade() -> None:
    bind = op.get_bind()

    # 1. Types first, before anything references them.
    DEPLOYMENT_TYPE.create(bind, checkfirst=False)
    DEPLOYMENT_STATUS.create(bind, checkfirst=False)
    HEALTH_STATUS.create(bind, checkfirst=False)

    # 2. clusters -- the parent every other table points at.
    #    gen_random_uuid() comes from pgcrypto, installed by infra/postgres/initdb.sql.
    op.create_table(
        "clusters",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("deployment_type", DEPLOYMENT_TYPE, nullable=False),
        sa.Column(
            "deployment_status",
            DEPLOYMENT_STATUS,
            server_default=sa.text("'pending'::deployment_status"),
            nullable=False,
        ),
        sa.Column("milvus_version", sa.Text(), nullable=True),
        sa.Column("endpoint_uri", sa.Text(), nullable=False),
        sa.Column("metrics_uri", sa.Text(), nullable=True),
        sa.Column("object_store_endpoint", sa.Text(), nullable=True),
        sa.Column("compose_project", sa.Text(), nullable=True),
        sa.Column("namespace", sa.Text(), nullable=True),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.Column("last_health_check_at", TZ, nullable=True),
        sa.Column(
            "last_health_status",
            HEALTH_STATUS,
            server_default=sa.text("'unknown'::health_status"),
            nullable=False,
        ),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_clusters"),
        sa.UniqueConstraint("name", name="uq_clusters_name"),
    )
    op.create_index("ix_clusters_deployment_status", "clusters", ["deployment_status"])
    # Partial index: soft-deleted clusters are excluded from every list query,
    # so keeping them out of the index keeps it small and index-only scannable.
    op.create_index(
        "ix_clusters_active",
        "clusters",
        ["deployment_status"],
        postgresql_where=sa.text("deployment_status <> 'deleted'"),
    )

    # 3. health_checks -- append-only time series.
    op.create_table(
        "health_checks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cluster_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("checked_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.Column("status", HEALTH_STATUS, nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("milvus_reachable", sa.Boolean(), nullable=False),
        sa.Column("object_store_reachable", sa.Boolean(), nullable=True),
        sa.Column("metadata_store_reachable", sa.Boolean(), nullable=True),
        sa.Column("server_version", sa.Text(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name="fk_health_checks_cluster_id_clusters",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_health_checks"),
    )
    op.create_index(
        "ix_health_checks_cluster_id_checked_at",
        "health_checks",
        ["cluster_id", sa.text("checked_at DESC")],
    )

    # 4. component_status -- append-only container/pod observations.
    op.create_table(
        "component_status",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cluster_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("component_name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        # Nullable: a component reconciled as 'missing' has no container to name.
        sa.Column("runtime_id", sa.Text(), nullable=True),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("health", sa.Text(), nullable=True),
        sa.Column("restart_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("started_at", TZ, nullable=True),
        sa.Column("observed_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name="fk_component_status_cluster_id_clusters",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_component_status"),
    )
    op.create_index(
        "ix_component_status_cluster_id_component_name_observed_at",
        "component_status",
        ["cluster_id", "component_name", sa.text("observed_at DESC")],
    )

    # 5. collection_snapshots -- append-only per-collection statistics.
    op.create_table(
        "collection_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cluster_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("collection_name", sa.Text(), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("num_partitions", sa.Integer(), nullable=True),
        sa.Column("dimension", sa.Integer(), nullable=True),
        sa.Column("index_type", sa.Text(), nullable=True),
        sa.Column("metric_type", sa.Text(), nullable=True),
        sa.Column("is_loaded", sa.Boolean(), nullable=True),
        sa.Column("observed_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name="fk_collection_snapshots_cluster_id_clusters",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_collection_snapshots"),
    )
    op.create_index(
        "ix_collection_snapshots_cluster_id_collection_name_observed_at",
        "collection_snapshots",
        ["cluster_id", "collection_name", sa.text("observed_at DESC")],
    )

    # 6. events -- audit and incident trail.
    #    ON DELETE SET NULL, not CASCADE: the incident history must outlive a
    #    hard-deleted cluster, since that history is the point of the table.
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cluster_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name="fk_events_cluster_id_clusters",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_events"),
    )
    op.create_index("ix_events_created_at", "events", [sa.text("created_at DESC")])
    op.create_index(
        "ix_events_cluster_id_created_at",
        "events",
        ["cluster_id", sa.text("created_at DESC")],
    )


def downgrade() -> None:
    bind = op.get_bind()

    # Reverse order: children before the parent, types last of all -- dropping
    # a type still referenced by a column raises a dependency error.
    # DROP TABLE removes that table's own indexes, so they need no explicit drop.
    op.drop_table("events")
    op.drop_table("collection_snapshots")
    op.drop_table("component_status")
    op.drop_table("health_checks")
    op.drop_table("clusters")

    HEALTH_STATUS.drop(bind, checkfirst=False)
    DEPLOYMENT_STATUS.drop(bind, checkfirst=False)
    DEPLOYMENT_TYPE.drop(bind, checkfirst=False)
